import type { Difficulty, EmployeeSizeRange } from "@/lib/types";

// English UI copy for frontend-user, mirroring vi.ts's exact key structure —
// see docs/business/vision.md#phase-amendment--2026-08-06 (US-49/50).
// AI-translated, no human review gate, per that amendment. Never imported
// directly by components — go through "./index" (`getText`/`useText`).
export const en = {
  header: {
    navAriaLabel: "Main",
    homeLink: "Home",
    questionsLink: "Questions",
    companiesLink: "Companies",
    subscribeLink: "Pricing",
    bookmarksLink: "Saved questions",
    profileLink: "Profile",
    logoutLabel: "Log out",
    loginLink: "Log in",
    loginRegisterLink: "Log in / Register",
    closeMenuLabel: "Close menu",
    openMenuLabel: "Open navigation menu",
  },
  footer: {
    tagline: "An interview practice platform for the Vietnamese job market.",
  },
  themeToggle: {
    switchToLight: "Switch to light mode",
    switchToDark: "Switch to dark mode",
  },
  common: {
    loading: "Loading…",
    or: "or",
    goToLoginLink: "Go to login",
    networkError: "Couldn't connect to the server. Check your network and try again.",
    passwordHint: (minLength: number) => `At least ${minLength} characters`,
    premiumBadge: "Premium",
    retryLabel: "Try again",
    genericErrorTitle: "Something went wrong",
    genericErrorBody: "Please try again. If this keeps happening, come back later.",
    notFoundTitle: "Page not found",
    notFoundBody: "The page you're looking for doesn't exist or has moved.",
    backToHomeLink: "Back to home",
  },
  auth: {
    login: {
      pageTitle: "Log in",
      heading: "Log in",
      subtitle: "Log in to keep practicing.",
      emailLabel: "Email",
      passwordLabel: "Password",
      forgotPasswordLink: "Forgot password?",
      submitLabel: "Log in",
      submitLoading: "Logging in…",
      googleLabel: "Continue with Google",
      noAccount: "Don't have an account?",
      createAccountLink: "Create an account",
      errors: {
        emailNotVerified:
          "Email not verified yet. Check your inbox for the verification link before logging in.",
        invalidCredentials: "Incorrect email or password.",
      },
    },
    register: {
      pageTitle: "Create account",
      heading: "Create account",
      subtitle: "Create a free account to save questions and practice.",
      emailLabel: "Email",
      passwordLabel: "Password",
      submitLabel: "Create account",
      submitLoading: "Creating account…",
      googleLabel: "Sign up with Google",
      haveAccount: "Already have an account?",
      loginLink: "Log in",
      emailTakenPrefix: "This email is already registered.",
      emailTakenLoginLink: "Log in",
      emailTakenSuffix: "or use a different email.",
      errors: {
        validationError: "Please check the email and password you entered.",
      },
      success: {
        title: "Check your email to verify your account",
        bodyBeforeEmail: "We sent a verification email to ",
        bodyAfterEmail: ". You need to verify it before logging in.",
      },
    },
    forgotPassword: {
      pageTitle: "Forgot password",
      heading: "Forgot password",
      emailLabel: "Email",
      submitLabel: "Send reset link",
      submitLoading: "Sending…",
      success: {
        title: "Check your email",
        bodyBeforeEmail: "If ",
        bodyAfterEmail: " has an account, we sent a password reset link to it.",
      },
    },
    resetPassword: {
      pageTitle: "Reset password",
      heading: "Reset password",
      newPasswordLabel: "New password",
      confirmPasswordLabel: "Confirm new password",
      mismatchError: "Passwords don't match.",
      submitLabel: "Reset password",
      submitLoading: "Resetting…",
      missingToken: {
        title: "Missing reset code",
        body: "Open the link directly from the email you received.",
      },
      success: {
        title: "Password reset",
        body: "All previous sessions have been signed out. Log in again with your new password.",
      },
      errors: {
        tokenExpired: "This reset link has expired. Request a new one.",
        tokenUsed: "This link has already been used. Request a new one if you still need to reset.",
        tokenInvalid: "Invalid reset link. Double-check the link in your email.",
      },
    },
    verifyEmail: {
      pageTitle: "Verify email",
      heading: "Verify email",
      verifyingSrOnly: "Verifying…",
      verifyingBody: "Verifying your email…",
      status: {
        success: { title: "Email verified", body: "You can log in now." },
        expired: {
          title: "Verification link expired",
          body: "Register again or contact support for a new verification link.",
        },
        used: {
          title: "This link has already been used",
          body: "Your account may already be verified — try logging in.",
        },
        invalid: {
          title: "Invalid verification link",
          body: "Double-check the link in your email, or request a new one.",
        },
        missing: {
          title: "Missing verification code",
          body: "Open the link directly from the email you received, rather than typing this page's address.",
        },
      },
    },
    googleCallback: {
      pageTitle: "Logging in",
      completingSrOnly: "Completing login…",
      completingBody: "Completing login…",
      failedTitle: "Couldn't log in with Google",
      failedBody: "You may have cancelled on Google, or the sign-in session expired.",
      backToLoginLink: "Back to login",
    },
  },
  questions: {
    difficultyLabel: {
      EASY: "Easy",
      MEDIUM: "Medium",
      HARD: "Hard",
    } satisfies Record<Difficulty, string>,
    list: {
      pageHeading: "Interview questions",
      pageIntro: "Practice with a real question set, organized by topic.",
      categoryPageHeadingPrefix: "Interview questions",
      categoryPageIntroPrefix: "Practice with a real question set on",
      emptyTitle: "No matching questions found",
      emptyBody: "Try loosening the filters or changing your search terms.",
      meta: {
        titlePagePrefix: "page",
        descriptionBase: "A real interview question set",
        descriptionCategoryPrefix: "topic",
        descriptionDifficultyPrefix: "difficulty",
        descriptionTagPrefix: "tag",
        descriptionSuffix: "Practice for free, unlock detailed answers with Premium.",
        categoryDescription: (categoryName: string) =>
          `Interview question set for ${categoryName}. Practice for free, unlock detailed answers with Premium.`,
      },
    },
    detail: {
      breadcrumbAriaLabel: "Breadcrumb",
      answerHeading: "Answer",
      noAnswerYet: "This question doesn't have an answer yet.",
      revealAnswerCta: "Show answer",
      meta: {
        descriptionPrefix: "Interview question",
        descriptionCategoryInfix: "on",
        descriptionPremium: "Unlock the detailed answer with Premium.",
        descriptionFree: "See the detailed answer for free.",
      },
      premiumAnswer: {
        checkingAccessSrOnly: "Checking access…",
        checkFailedTitle: "Couldn't check access",
        checkFailedBody: "Check your network and try again.",
        gatedTitle: "Premium member content",
        gatedBodyLoggedIn: "Upgrade to Premium to see the full answer.",
        gatedBodyLoggedOut: "Log in and upgrade to Premium to see the full answer.",
        upgradeCta: "Upgrade now",
        loginCta: "Log in",
      },
    },
    filters: {
      formAriaLabel: "Filter questions",
      categoryLabel: "Topic",
      allCategories: "All topics",
      difficultyLabel: "Difficulty",
      allDifficulties: "All difficulties",
      planLabel: "Plan",
      allPlans: "All",
      freePlan: "Free",
      premiumPlan: "Premium",
      searchLabel: "Search",
      searchPlaceholder: "Enter a keyword...",
      searchSubmit: "Search",
      markStudyingLabel: "Mark as studying",
      unmarkStudyingLabel: "Studying this topic",
      tagLabel: "Tag",
      allTags: "All tags",
      tagsSelectedLabel: (n: number) => `${n} tag${n === 1 ? "" : "s"} selected`,
      clearTagsLabel: "Clear",
      activeTagsPrefix: "Tag:",
      removeTagAriaLabel: (tag: string) => `Remove tag ${tag}`,
    },
    pagination: {
      ariaLabel: "Pagination",
      prev: "Previous",
      next: "Next",
      pageOf: (page: number, totalPages: number) => `Page ${page} / ${totalPages}`,
    },
  },
  companies: {
    list: {
      pageHeading: "Company directory",
      pageIntro: "Look up company information to prepare better for interviews.",
      emptyTitle: "No matching companies found",
      emptyBody: "Try different search terms.",
      meta: {
        titlePagePrefix: "page",
        description: "A company directory to help you prepare for interviews.",
      },
    },
    detail: {
      breadcrumbAriaLabel: "Breadcrumb",
      meta: {
        descriptionPrefix: "Company info",
      },
      employeeSizeRangeLabel: {
        UNDER_50: "Under 50 employees",
        RANGE_50_200: "50–200 employees",
        RANGE_200_1000: "200–1,000 employees",
        RANGE_1000_5000: "1,000–5,000 employees",
        OVER_5000: "Over 5,000 employees",
      } satisfies Record<EmployeeSizeRange, string>,
      websiteLinkLabel: "Company website",
      industriesAriaLabel: "Industries",
    },
    filters: {
      formAriaLabel: "Search companies",
      searchLabel: "Search",
      searchPlaceholder: "Enter a company name...",
      searchSubmit: "Search",
    },
    reviews: {
      heading: "Company reviews",
      emptyBody: "No reviews for this company yet.",
      ratingAriaLabel: (rating: number) => `${rating} out of 5 stars`,
      status: {
        PENDING: "Pending approval",
        REJECTED: "Rejected",
      },
      adminReplyLabel: "Reply from the team",
      deleteLabel: "Delete",
      reportLabel: "Report",
      reportedLabel: "Reported",
      form: {
        heading: "Write a review",
        loginPromptBefore: "",
        loginPromptLink: "Log in",
        loginPromptAfter: " to write a review for this company.",
        ratingLabel: "Your rating",
        ratingStarAriaLabel: (value: number) => `${value} star${value === 1 ? "" : "s"}`,
        contentLabel: "Review",
        contentPlaceholder: "Share your experience working here...",
        anonymousLabel: "Post anonymously",
        submitLabel: "Submit review",
        submittedNotice: "Thanks! Your review is pending admin approval.",
      },
    },
  },
  bookmarks: {
    toggle: {
      addLabel: "Save question",
      removeLabel: "Remove bookmark",
    },
    list: {
      pageTitle: "Saved questions",
      pageHeading: "Saved questions",
      pageIntro: "Questions you've saved to review later.",
      loadingSrOnly: "Loading saved questions…",
      emptyTitle: "You haven't saved any questions yet",
      emptyBody: "Tap the save icon on a question to add it here.",
      browseQuestionsLink: "Browse questions",
      errorTitle: "Couldn't load saved questions",
      errorBody: "Check your network and try again.",
      signedOutTitle: "Log in to see saved questions",
      signedOutBody: "You need to log in to save and review questions.",
    },
  },
  profile: {
    pageTitle: "Your profile",
    pageHeading: "Your profile",
    emailLabel: "Email",
    displayNameLabel: "Display name",
    displayNameHint: "Shown instead of your email in public places, like company reviews. Optional.",
    displayNamePlaceholder: "No display name set",
    saveLabel: "Save changes",
    savingLabel: "Saving…",
    saveSuccess: "Display name saved.",
    saveError: "Couldn't save. Please try again.",
    signedOutTitle: "Log in to see your profile",
    signedOutBody: "You need to log in to view and edit your profile.",
  },
  subscription: {
    planName: {
      MONTHLY: "Monthly Plan",
      LIFETIME: "Lifetime Plan",
    } as Record<string, string>,
    subscribe: {
      pageTitle: "Upgrade to Premium",
      pageHeading: "Choose a Premium plan",
      pageIntro: "Unlock full, detailed answers for every interview question.",
      loadingSrOnly: "Loading plans…",
      errorTitle: "Couldn't load plans",
      errorBody: "Check your network and try again.",
      emptyTitle: "No plans available right now",
      lifetimeBadge: "Lifetime, never expires",
      recommendedBadge: "Most popular",
      freeTitle: "Free",
      freePriceLabel: "$0",
      freeDescription: "Read every question, including free ones, no account needed.",
      freeCta: "Browse free questions",
      planDescription: {
        MONTHLY: "Good for a quick refresh before a specific round of interviews.",
        LIFETIME: "Pay once, use forever — no renewal needed.",
      } as Record<string, string>,
      paymentNote: "Secure payment via VNPay",
      selectCta: "Choose this plan",
      selectCtaLoading: "Redirecting to VNPay…",
      signedOutTitle: "Log in to upgrade",
      signedOutBody: "You need to log in before choosing a Premium plan.",
      alreadySubscribed: {
        title: "You're already a Premium member",
        bodyLifetime: "Your Lifetime plan never expires.",
        bodyWithExpiry: (date: string) => `Your current plan is valid until ${date}.`,
      },
      checkoutError: "Couldn't start checkout. Please try again.",
    },
    callback: {
      pageTitle: "Confirming payment",
      confirmingSrOnly: "Confirming payment…",
      confirmingBody: "Confirming your payment with VNPay. Please wait a moment…",
      successTitle: "Payment successful",
      successBody: "Your account has been upgraded to Premium.",
      goToQuestionsLink: "See Premium questions",
      pendingTitle: "Payment confirmation not received yet",
      pendingBody:
        "We haven't received payment confirmation from VNPay yet. If your payment succeeded, this page will update automatically in a few minutes — otherwise, please try again.",
      retryLink: "Try again",
      backToSubscribeLink: "Back to plan selection",
      signedOutTitle: "Couldn't determine your session",
      signedOutBody: "Log in again to check your payment status.",
    },
  },
  home: {
    siteDescription: "Practice interviews with a real question set, organized by topic.",
    heroBody: "Practice interviews with a real question set, organized by topic.",
    browseQuestionsLink: "Browse questions",
    loginLink: "Log in",
    createAccountLink: "Create account",
    eyebrow: "$ interview-training --topic=all --level=junior..senior",
    heroHeadingBeforeMark: "Practice interviews with real questions, ",
    heroHeadingMark: "with suggested answers",
    heroSub:
      "Browse interview questions by topic and difficulty, answer them yourself first, then compare against the suggested answer — every question is free to read, unlock full answers with a paid plan.",
    searchPlaceholder: "e.g. event loop, React hooks, database normalization...",
    searchSubmit: "Search",
    searchAriaLabel: "Search interview questions",
    flashcard: {
      tagLabel: "QUESTION #128",
      category: "JavaScript",
      questionBeforeMark: "Explain how the ",
      questionMark: "event loop",
      questionAfterMark: " works.",
      reviewedLabel: "Reviewed 3 times",
    },
    categoriesHeading: "Browse by topic",
    categoriesCaption: "Pick a topic to start practicing.",
    categoriesQuestionCount: (total: number) => `(${total} questions)`,
    categoriesViewAll: "View all →",
    benefits: [
      {
        title: "Focused practice",
        body: "Filter questions by topic and difficulty, and focus on your weak spots instead of reading everything.",
      },
      {
        title: "Detailed suggested answers",
        body: "Every Premium question comes with a full suggested answer, so you know exactly what you're missing.",
      },
      {
        title: "Save for later",
        body: "Bookmark questions to come back to before your interview day.",
      },
    ],
    howItWorksHeading: "How it works",
    steps: [
      { title: "Pick a topic and level", body: "Browse the question catalog or search by keyword." },
      { title: "Answer it yourself first", body: "Read the question and try answering it like a real interview." },
      {
        title: "Compare with the suggested answer",
        body: "Free questions are visible right away; Premium questions unlock the answer with a paid plan.",
      },
    ],
    ctaHeading: "Ready to practice more seriously?",
    ctaBody: "Unlock every suggested answer with Premium.",
    ctaLink: "See pricing",
    faqHeading: "Frequently asked questions",
    faq: [
      {
        question: "Do I have to pay to see the questions?",
        answer:
          "No. Every question is always free to read, even if you're not logged in. Only the suggested answer for Premium questions requires a paid plan.",
      },
      {
        question: "What's different about Premium questions?",
        answer:
          "Premium questions show the full question as normal, but the \"suggested answer\" section only appears if your account has an active plan.",
      },
      {
        question: "What payment methods can I use?",
        answer: "Payment is via VNPay. See the Pricing page for plan details.",
      },
    ],
  },
} as const;
